spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/gut_bank
    username: root
    password: Igibu777

  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
#classpath:liquibase/changelog:


logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG

app:
  server:
    url: ${app.server.url}



