
#spring.jpa.hibernate.ddl-auto=none
#spring.datasource.url=jdbc:mysql://localhost:3306/gut_bank
#spring.datasource.url=jdbc:mysql://localhost:3306/geek_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=Igibu777
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql: true
#
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
#
#liquibase:
#change-log: classpath:/db/changelog/changelog-master.xml
spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/gut_bank
    username: root
    password: Igibu777

  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG

app:
  server:
    url: ${app.server.url}



