spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: dev
  main:
    banner-mode: off

  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}

  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG

app:
  server:
    url: ${app.server.url}